
language: python
python:
    - "2.7"

install:
    - "pip install ."
    - "pip install nose pylint"
script:
    - "2048.py --help"
    - "nosetests -I browser -v"
    - "pylint 2048 engine helpers"

branches:
    only:
        - master
        - next

