
language: python
python:
    - "2.7"

before_install:
    - "phantomjs --version"

install:
    - "pip install nose nose-cov pylint"
    - "make install"
script:
    - "make test_install"
    - "make test"

branches:
    only:
        - master

