
language: python
python:
    - "2.7"

install:
    - "pip install ."
    - "pip install nose"
script:
    - "2048.py --help"
    - "nosetests -I browser -v"

branches:
    only:
        - master
        - next

